# permissions for end users to view entandoingressv2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: entandoingressv2-viewer-role
rules:
- apiGroups:
  - plugin.entando.org
  resources:
  - entandoingressv2s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - plugin.entando.org
  resources:
  - entandoingressv2s/status
  verbs:
  - get
